/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui.view;

import java.awt.Color;

/**
 *
 * @author ASUS X
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        PanelKiri.setVisible(false);
        PanelKiri.setBackground(new Color(0,0,0,64));
        Tokoname.setBackground(new Color(0,0,0,0));
        Password.setBackground(new Color(0,0,0,0));
        Username.setBackground(new Color(0,0,0,0));
        Pin.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tokoname = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        Pin = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        PanelKiri = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        LoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tokoname.setForeground(new java.awt.Color(255, 255, 255));
        Tokoname.setBorder(null);
        getContentPane().add(Tokoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, -1));

        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setBorder(null);
        Username.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, -1));

        Pin.setForeground(new java.awt.Color(255, 255, 255));
        Pin.setBorder(null);
        getContentPane().add(Pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 210, -1));

        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(null);
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 210, -1));

        PanelKiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setText("Username");
        PanelKiri.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setText("Pin Admin");
        PanelKiri.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setText("Password");
        PanelKiri.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setText("Nama Toko");
        PanelKiri.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));
        PanelKiri.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 10));
        PanelKiri.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 210, 10));
        PanelKiri.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, 10));
        PanelKiri.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 10));

        jToggleButton1.setText("Submit");
        PanelKiri.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        getContentPane().add(PanelKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 530));

        LoginPanel.setBackground(new java.awt.Color(51, 255, 51));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("User           :");
        LoginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("\"Logo\"");
        LoginPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/view/buleud.png"))); // NOI18N
        LoginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password   :");
        LoginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Register?");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        LoginPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        jLabel6.setText("Login");
        LoginPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        getContentPane().add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 790, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       PanelKiri.setVisible(true);
 
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel PanelKiri;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Pin;
    private javax.swing.JTextField Tokoname;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
